### ISSUE TITLE
Spotify: Cover Art not showing

### ISSUE THREAD

**Issue by Arynthesizer** [MarcoPixel/Monstercat-Visualizer#101]
Hi! I'm the same guy from #77 and I'm having a new problem.

Basically, my cover art is stuck on the classic Monstercat one. The option is unchecked, and I have gone through the variables to make sure. I already have done all of the steps suggested in #77 from last time. The rest of the metadata shows fine.

![screenshot_79](https://user-images.githubusercontent.com/31020677/31588871-22cd7372-b1c6-11e7-9b54-1445789043f4.png)

I get that error message in the log (seen in the screenshot) every time I refresh the cover art

Thanks!

**Comment by MarcoPixel** [comment]
Install the newest version of the Spotify plugin (https://forum.rainmeter.net/download/file.php?id=15162) and then refresh all skins. It should open a webpage where you have to allow permissions for SpotifyPlugin, do that and then check if it's working.

Otherwise remove the **coverSpotify.png** under **Documents\Rainmeter\Skins\Monstercat-Visualizer\@Resources\images** and restart Spotify and Rainmeter.

**Comment by Arynthesizer** [comment]
Huh, removing coverSpotify.png seemed to work. Thanks!

**Comment by MarcoPixel** [comment]
Great, glad that it worked out for you :)
