### ISSUE TITLE
Can't drag visualizer above bottom half of screen 

### ISSUE THREAD

**Issue by Corco42** [MarcoPixel/Monstercat-Visualizer#103]
My visualizer bar can only be dragged to the middle of the screen. For instance, I want to put it in the top left corner of my desktop, but it only reaches the middle point of my screen and cannot be drug higher. See screenshot of desktop for example. 

Thanks! 
 
![visual_desktop](https://user-images.githubusercontent.com/33294530/32291804-25ad0582-bf0c-11e7-9127-8c09572bbdd0.PNG)

**Comment by tjhrulz** [comment]
You will need to lower the visualizer height in order to move it up there, you will find in the general section of the settings.

You also can turn off keep on screen (Found under the rainmeter settings in the rightclick menu not the normal settings skin) however due to windows you can not drag it above the top of a display and the only way around it is to manually edit the skins Y position in the Rainmeter.ini. However this would cause the bars to go off screen and is not recommended.
