### ISSUE TITLE
plz add VLC Support

### ISSUE THREAD

**Issue by ZmanGamer** [MarcoPixel/Monstercat-Visualizer#108]
#i need it because i use vlc media player

**Comment by tjhrulz** [comment]
I have to inform you that VLC 2.1 or higher is no longer supported with Rainmeter, VLC sadly made several changes to its plugin system so the CAD plugin is broken. I looked at updating it once but it seems part of the API it used no longer exist. There are some few workarounds in the official forums but for now i will remove the support because the workaround is quite hacky and might even not work.

Please check out the [forum post](https://forum.rainmeter.net/viewtopic.php?f=14&t=16981&start=10)  regarding VLC player no longer working for more information. 

If you do decide to just downgrade selecting any CD Art Display based player in the settings will make it work with VLC (Foobar or Musicbee)
