### ISSUE TITLE
Support For Tidal

### ISSUE THREAD

**Issue by KaosC57** [MarcoPixel/Monstercat-Visualizer#135]
I just found Tidal, and I'm probably going to switch from Spotify to Tidal, but there's currently no Tidal support. I'd love for support to be added if possible!

**Comment by tjhrulz** [comment]
Support for Tidal's web player exists as part of the WebNowPlaying plugin and browser extension (Although there is a small issue where position is not updated when the page is not visible) however support for their Windows Store app is not possible at this time.

So as long as you are willing to use their player in Chrome/Vivaldi or Firefox then Monstercat Visualizer already supports it.

**Comment by KaosC57** [comment]
Sorry, I can't willingly use the Webapp since I'd rather keep my applications running separately. And, It still uses Flash, and... I don't want to install Flash on Firefox... That's stupid in 2018. I'm using the Non-Windows Store application to run Tidal, their standalone application from the website.

**Comment by tjhrulz** [comment]
My bad I was thinking of Deezer (Which is a windows 10 app). Tidal's app is also not able to be supported, and for the record as actually just a wrapped for an older version of Chrome so really the only gain is that it is in a separate window.

It is possible that if someone could find a way to inject code into the webpage they load then they could just inject the two scripts from WNP's browser extension and it should work so long as the version of Chrome is not too old, but the options for injection are limited since they use HTTPS.

**Comment by KaosC57** [comment]
Ah, so... It's actually wow... That's such a dumb way of programming that. I might as well just install Flash into Firefox and get WNP. Thanks for enlightening me.

**Comment by tjhrulz** [comment]
No problem. I am trying to see if you can open a web page standalone in Firefox, I know you can in chrome and it turns out pretty nice and even gets its own space in the taskbar 
![example](https://user-images.githubusercontent.com/4722934/35662434-18651a32-06e6-11e8-9fd1-5ad6061d4141.png)
