### ISSUE TITLE
No album art for local files in Spotify

### ISSUE THREAD

**Issue by cptncrnsh** [MarcoPixel/Monstercat-Visualizer#140]
I always get the monstercat logo as my album art for local music that i added to spotify. The album covers are correctly displayed in spotify.

### Versions

* Rainmeter Version: 4.1.0 r2989 64-bit (Nov 6 2017)
* OS Version: Windows 10 Pro 64-bit (build 16299)
* Skin Version: 1.8.1
* Spotify Version: 1.9.2.0

**Comment by tjhrulz** [comment]
Replicated on my end, I am investigating this as we speak however likely this is something that is an issue with the Spotify Rainmeter plugin and I will have to work with .raptor on to get fixed.

**Comment by tjhrulz** [comment]
After further investigation yet of the issue Spotify's local API does not support grabbing the album art of local files being played. There may be a way to fix it for premium users in hacky way but it will require the effort of about 3 different people and may not work due to limitations of Spotify's official API https://developer.spotify.com/web-api/local-files-spotify-playlists/ . 

For now I am going to have to close this issue, if we are able to find a workaround I will post an update here. Sadly this is an issue with Spotify's API is not being built with local files in mind and is partially locked off for non premium users.

**Comment by cptncrnsh** [comment]
One thing  I have noticed is, that very rarely the album art from the local songs is grabbed and lands in documents\Rainmeter\Skins\monstercat-visualizer\@Resources\images but it is still not displayed in the skin itself
