### ISSUE TITLE
Song informations still not cliping correctly

### ISSUE THREAD

**Issue by DDarkstorm** [MarcoPixel/Monstercat-Visualizer#149]
### Description
The update did nothing on the problem, the song informations are still too long

### Versions
* Rainmeter Version: 4.1.0 r2989
* OS Version: Windows 10
* Skin Version: Last version installed manually

### Additional notes/images
![txbabfj](https://user-images.githubusercontent.com/9608429/37682461-eb30e7f2-2c89-11e8-9473-3161e6f1a444.png)

**Comment by MarcoPixel** [comment]
This is because the album cover is not included with the clipping area, if you want to add it manually you have to go under `@Resources/include/MeasureStyling.inc` and change the `[MeasureClipSongInformation]` to the following:

```
[MeasureClipSongInformation]
Measure=Calc
Formula=#ClipSongInformation#
IfEqualValue=1
IfEqualAction=[!SetOption MeterArtist W "#SkinWidth#-(200*#ScaleSongInformation#)"][!SetOption MeterTrack W "#SkinWidth#-(200*#ScaleSongInformation#)"]
IfBelowValue=1
IfBelowAction=[!SetOption MeterArtist ClipString 2]
UpdateDivider=-1
```
I might add a setting sometimes in the future to just toggle it, but it wouldn't be accurate as the positioning of the cover is still dependent on the users layout.

**Comment by DDarkstorm** [comment]
Thanks, that resolved my issue.

Great work man

**Comment by MarcoPixel** [comment]
@DDarkstorm No problem, thanks for hanging around 👍
