### ISSUE TITLE
Typo in a toggle description

### ISSUE THREAD

**Issue by fluffycq** [MarcoPixel/Monstercat-Visualizer#151]
### Description

My problem is there is a typo in one of the toggles. It says "This will cause the visualizer to ignore any sound when the media player is **noy** playing a song or detected."

### Versions

* Rainmeter Version: 4.1.0 r2989 (64-bit PC)
* OS Version: Windows 10 Home (64-bit build 16299)
* Skin Version: 1.8.1
* Spotify Version: 1.3.0.0

### Additional notes/images

https://i.imgur.com/ADuekzm.png

**Comment by tjhrulz** [comment]
This has been fixed since the release, if you wish to install the newest version of Monstercat Visualizer manually which is hopefully free of my typing mistakes see here: https://github.com/MarcoPixel/Monstercat-Visualizer#manual-installation

Also why does everyone have to point out my inability to type :P
