### ISSUE TITLE
Groove  music player is not playing

### ISSUE THREAD

**Issue by viaerra** [MarcoPixel/Monstercat-Visualizer#158]
Groove music player  is  not working in lano- visualizer.
### Description

i was trying to visualize GROOVE music player but  its not visualizing, tried every way to  sort-out  that problem  but I'm unable to get  any solution. SO  please help me  out.
### Versions

[rain meter  version-4.1.]

* Rainmeter Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* OS Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* Skin Version: [You can check this here: Right-Click the Skin -> Open variables file. It should be at the top of the file]
* Spotify Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#PluginsTab]

### Additional notes/images

[If you have any additional infos you can give us, please write them down]

**Comment by tjhrulz** [comment]
1. This is the repo for Monstercat Visualizer and thus not the place to report issues with Lano
2. Even if it was Groove Music is not supported in either Monstercat or Lano Visualizer
3. No Rainmeter skin supports Groove music as support for it is impossible with the way Microsoft has configured it since there is no API for it nor is there a way for us to strip info from it. There are many other great music players out there for Windows that Rainmeter does support and I would recommend switching to one of them.
