### ISSUE TITLE
Current Audio Device: 0

### ISSUE THREAD

**Issue by AzureNotAzure** [marcopixel/Monstercat-Visualizer#166]
### Description

Help! My visualizer is not working. The cover, song titles/artists are working but my visualizer isn't. It isn't picking up any of my audio devices and is saying that my current audio device is 0.

Versions:
Windows 10
Rainmeter: 4.1.0 
Spotify: 1.0.80.474
Visualizer: 1.8.1

![image](https://user-images.githubusercontent.com/39469976/40284341-0700a99a-5c4b-11e8-9e62-0b7b85a7155d.png)
![image](https://user-images.githubusercontent.com/39469976/40284349-1f142b7e-5c4b-11e8-9b2c-f51a5ce1e7e6.png)

I've tried switching audio devices, restarting, and reinstalling both my audio devices and the visualizer to no avail. Thank you very much in advance.

**Comment by MarcoPixel** [comment]
Some USB headphones do not work properly because the drivers are incompitable with the way the audio gets captured by Windows/Rainmeter. You could try and check if you have some sort of audio enhancers turned on, because they can cause issues with the audio capturing for the visualizer.

Try disabling them and then report back if disabling them worked :)

**Comment by AzureNotAzure** [comment]
Unfortunately, this did not work. It was working up until a few days
after I began using it, and booted up my pc. I did not have any
drivers updates prior to when this began happening.
