### ISSUE TITLE
Song informations only show the first artist (Spotify)

### ISSUE THREAD

**Issue by ThaumicTom** [MarcoPixel/Monstercat-Visualizer#184]
### Description

The song informations only display the first artist of any song played on Spotify. This happens all the time, thus it isn't necessarily needed to reproduce.

### Versions

* Rainmeter Version: 4.2.0 beta r3088 64-bit (Jun 15 2018) 
* OS Version: Windows 10 Home 1709 64-bit (build 16299)
* Skin Version: 2.0.2
* Spotify Version: SpotifyPlugin.dll: 2.1.5

### Additional notes/images

![image](https://user-images.githubusercontent.com/15818698/41676109-e20072fa-74c4-11e8-9ea0-c30c3012ecf1.png)
4 Artists can be seen, one is being shown (1 of them shouldn't necessarily be shown).

**Comment by MarcoPixel** [comment]
This is caused by the Spotify plugin and for me there's not much what i can do. 

I'll recommend creating an issue on [the SpotifyPlugin repo](https://github.com/RobertFrydenlund/SpotifyPlugin/) and see if he wants to add that feature. If he does, i will update the plugin and will post a comment here.

**Comment by ThaumicTom** [comment]
https://github.com/RobertFrydenlund/SpotifyPlugin/issues/14#event-1746199848 Should be fixed.
