### ISSUE TITLE
Many Players not Working (For me at least)

### ISSUE THREAD

**Issue by AWildLlama** [MarcoPixel/Monstercat-Visualizer#186]
### Description

Originally I couldn't get the skin to work with MediaMonkey, and I've found that the only one that is working for me is Spotify. I've tried others like MusicBee and Winamp, but all I get is NA for all info.

### Versions

* Rainmeter Version: Latest Beta Release (4.2 r3097)
* Skin Version: 2.0.2
* Spotify Version: 2.1.5

**Comment by MarcoPixel** [comment]
This is because MediaMonkey probably changed a lot in the last few updates, i'll recommend posting in the [official Rainmeter forums](https://forum.rainmeter.net) about this because the integration is via the NowPlaying plugin which is built into Rainmeter itself.

For MusicBee, you have to enable "CD Art Display" under Plugins to get it working.
[Here's an image on where to enable it.](https://media.discordapp.net/attachments/148718731743199233/354326491280048130/unknown.png?width=710&height=698)

For Winamp, it seems that it got some issues regarding the `DynamicVariables=1` setting i've used with this skin, but there's no real workaround since it requires it to get it working. Try downgrading to a lower version of Winamp and see if its working. [Read more about this issue on the official forums here!](https://forum.rainmeter.net/viewtopic.php?t=23315)
