### ISSUE TITLE
Pandora or Youtube?

### ISSUE THREAD

**Issue by Godliest** [MarcoPixel/Monstercat-Visualizer#19]
I really would appreciate it if you could have this work with pandora or youtube. Thank you!

**Comment by MarcoPixel** [comment]
What do you mean by "Pandora or Youtube"? 

If you want to get song information like Artist, song title or cover to work with both of them it will not be implemented because it's not part of the NowPlaying plugin and also it's not available as a standalone plugin (that might change in the future tho if more people request it on the rainmeter forums maybe, but dont get your hopes up).

But if you mean the audio visualization, it should work fine with any modern web browser right now.

**Comment by MarcoPixel** [comment]
Closed because of no response, please reopen this issue if you have any further questions.
