### ISSUE TITLE
Plex Support?

### ISSUE THREAD

**Issue by aaronth07** [marcopixel/Monstercat-Visualizer#227]
I'm wondering when/if there will be Plex Media Player (or Plexamp) support? That is my main media player since all of my content is FLAC.

**Comment by Azzhoe** [comment]
I would love to have Plex/Plexamp support as well! This is the most awesome music visualizer ever! Really wish this was available also on macOS as well.

**Comment by tjhrulz** [comment]
There was a limited plex support added using WebNowPlaying a while back, however keep it updated is a pain because plex purposefully built there stuff to prevent other from extracting info about it so there is nothing we can really do about that.

Also with this being a skin this is only going to be able to support what Rainmeter or someone who made a plugin for Rainmeter supports
