### ISSUE TITLE
Rainmeter keeps crashing when loading the visualizer 

### ISSUE THREAD

**Issue by Rohan-Debroy** [marcopixel/Monstercat-Visualizer#236]
### Description

[Whenever I try to load the visualizer it crashes rainmeter. Until I delete the rainmeter.ini the rainmeter keeps crashing]

[I tried updating the rainmeter to the latest beta version and also manually installing the skin.]

### Versions

[Rainmeter Version: 4.2 Final Release]
[OS Version: Windows 10 v1809]
[Skin Version: 2.0.2]

### Additional notes/images

[I am also attaching the log file.]
[Rainmeter.log](https://github.com/marcopixel/Monstercat-Visualizer/files/2729266/Rainmeter.log)

**Comment by Sleetui** [comment]
I also have this issue.  I don't recall updating Rainmeter or the Visualizer.

**Comment by d00m3dd00d** [comment]
-Open Explorer and type in %appdata%\Rainmeter in the navigation bar.

-Exit Rainmeter, if open.

-Temporarily rename Rainmeter.ini to Rainmetertemp.ini -- this will make Rainmeter launch with defaults.

-Once Rainmeter is launched, right click the Rainmeter icon in your task bar and enable Debug under Logging.

-Start adding your plugins again until you run into the crash/freeze

-Check the log under %appdata%\Rainmeter and post the errors.

I found this bug occurred to me when I enabled the Windows 10 Defender feature for Ransomware, which protects your Documents folder (among other folders). File access was denied in my logs, the plugin gets stuck in a loop. This is more of a Rainmeter bug than a bug for this plugin alone -- Rainmeter should handle disabling the plugin if it fails or otherwise watch for file access issues.

I was able to mitigate the issue by relocating the Plugins folder elsewhere (C:\Rainmeter for example) then editing rainmeter.ini to match the new location. I had no issues launching with my old config after that.

**Comment by Sid-Lais** [comment]
Thank you so much. The host file had a line '0.0.0.0 open.spotify.com' which made rainmeter crash. Removing it will make everything work well.

**Comment by d00m3dd00d** [comment]
Glad I could help. Windows is not good at letting users know when DEP or exploit protection is write-protecting files, which is sad. A good way to find these problems is combing the event logs for 0xc000005 (access denied, per Windows fault code charts, but they dont auto translate this)

**Comment by tjhrulz** [comment]
Yeah that windows feature is dumb, it's something that makes no sense whatsoever and there are better ways for windows protecting those kinds of issues. 

But yeah it is something that we have thought about creating a fallback for but given windows has given no directive on what they are doing with it and it has the ability to end up breaking poorly written skins we have refrained from doing that for the time being.

Thank you for helping out and I am glad you found an issue to your problem

**Comment by d00m3dd00d** [comment]
If this may help, these might be good practices for writing file paths for configs and data that has been a fairly constant location for a while:

%appdata%/whateverfolder for roaming data that follows the user profile
%appdatalocal%/whateverfolder for local data to the machine, good for something such as machine specific settings such as audio devices.

Variables will allow the administrator to modify the location they see fit for their environment and software will work as expected for those changes. Also isoftware is installer for all users, the application will reference the data in the user's context.

The appdata variable in Windows redirects to the current user's C:\Users\[user folder]\appdata\roaming is intended for apps to write configuration and temporary data to without administrator privileges., user profile folders like documents or desktop might break in specific scenarios such as folder redirection across a WAN connection or higher security workstations where application data manipulation by programs may not be intended

**Comment by cooldamie** [comment]
> Thank you so much. The host file had a line '0.0.0.0 open.spotify.com' which made rainmeter crash. Removing it will make everything work well.

where can I find the host file?

**Comment by Bread786** [comment]
> Thank you so much. The host file had a line '0.0.0.0 open.spotify.com' which made rainmeter crash. Removing it will make everything work well.

where do i find the host file?

**Comment by Sid-Lais** [comment]
I don't exactly remember the context, but I guess I was referring to the Windows host file, which is located at `C:\Windows\System32\drivers\etc\hosts`
