### ISSUE TITLE
No cover image with iTunes 12.9.3

### ISSUE THREAD

**Issue by mnewt00** [marcopixel/Monstercat-Visualizer#238]
### Description

Hi, I am not seeing the iTunes cover image for all songs, artists and albums.

### Versions

* Rainmeter Version: 4.3.0.3283 beta (64-bit) (I also tried the full release, it didn't work either)
* OS Version: Windows 10 Enterprise 1803 64-bit (build 17134) - English (3081)
* Skin Version: 2.0.2
* iTunes Version: 12.9.3

**Comment by Chewboko** [comment]
Likewise, but I am using AIMP not iTunes

**Versions**
- Rainmeter Version: 4.3.0.3298
- OS Version: Windows 10 Home 1809 64-bit (build 17763)
- Skin Version: 2.0.2
- AIMP Version: 4.51 (build 2084)

**Comment by tjhrulz** [comment]
iTunes may have broken Rainmeter support again, if it did happen there is likely nothing we can do about it  as we use an old API that iTunes had and Apple as of late has been against providing APIs like that.

As for the AIMP issue that is likely something seperate, double check you have it set up right and I would recommend heading over to the Rainmeter forums with help with that

**Comment by marcopixel** [comment]
iTunes Version 12.9.5.7 and AIMP V4.51 build 2084 both work on my machine perfectly fine.

@mnewt00 Check if you have the standalone version and not the Microsoft Store one since that one is not supported. If you have the Microsoft Store one, you can download the regular one here: https://www.apple.com/itunes/download/win64

**Comment by mnewt00** [comment]
Ty, the new update works, I can only play from playlists in my library but it works well
