### ISSUE TITLE
Solid background color

### ISSUE THREAD

**Issue by MaestroMagnifico** [MarcoPixel/Monstercat-Visualizer#24]
Hello. Can you guys add option in styling that allow to pick solid background color for visualizer? I'm using your software with OBS. And now I have to use green wallpapers for my desktop to be able to capture visualizer and make background transparent. Maybe I can do this in some ini file?

**Comment by MarcoPixel** [comment]
Hello MeastroMagnifico,

thanks for your feedback! Sadly i have to inform you that i will not implement your feature to the skin because it is really specific and it will probably not be used often.

You can try to create a simple skin with a solid color yourself with the help of the [Rainmeter documentation](https://docs.rainmeter.net/) and the official [Rainmeter forums](https://forum.rainmeter.net/).
