### ISSUE TITLE
N/A Artist Google play music desktop player (ytmusic)

### ISSUE THREAD

**Issue by Millie290** [marcopixel/Monstercat-Visualizer#243]
Hey,
I've got an issue with google play desktop music player using youtube music :
So it tell me N/A to artist when it switch to another song (exept if it's two time the same artist)
![ça marche pa](https://user-images.githubusercontent.com/44525457/57094800-add80d80-6d11-11e9-88b6-65355a36e48a.PNG)
maybe someone has solved this
thanks for your help ^^

**Comment by tjhrulz** [comment]
Unfortunately this is an issue on GPMDP's end. This skin just uses the GPMDP Rainmeter plugin which just implements GPMDP's WebSocket API and GPMDP's dev has been moving and while updates have happened they have not been pushed to live due to him not having his normal PC so most people are on a very outdated build.

You could download the latest GPMDP release candidate which should be pushed to everyone soon but be warned there be dragons ahead as the buld likely has many bugs in it https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3548

**Comment by Millie290** [comment]
> 
> 
> Unfortunately this is an issue on GPMDP's end. This skin just uses the GPMDP Rainmeter plugin which just implements GPMDP's WebSocket API and GPMDP's dev has been moving and while updates have happened they have not been pushed to live due to him not having his normal PC so most people are on a very outdated build.
> 
> You could download the latest GPMDP release candidate which should be pushed to everyone soon but be warned there be dragons ahead as the buld likely has many bugs in it [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3548](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3548)

Now it just don't change the name of all so ^^
