### ISSUE TITLE
Suggestion: Support for TIDAL.

### ISSUE THREAD

**Issue by purpl3F0x** [marcopixel/Monstercat-Visualizer#254]
### Description
It would be nice if you could add support for TIDAL. I have made a project to get the current playing song and artist from windows/osx and i have reversed engineered their api to get info like runtime album etc. I can pack those in a static lib if someone wants to integrate that with the project because I have no idea on making plugins for rainmaker.

**Comment by marcopixel** [comment]
For TIDAL support, we recommend using WebNowPlaying since it supports it via your webbrowser. For the reverse engineered API, i'll recommend you to post it to the forums or discord and find someone who would help you with this project.

Right now, i will close this issue as there is no way for me to add this to the skin, but feel free to reopen if you found someone which can help you :)

/cc @tjhrulz
