### ISSUE TITLE
Adding Visualizer to Streamlabs Apps?

### ISSUE THREAD

**Issue by Onyxx666** [marcopixel/Monstercat-Visualizer#259]
### Description

Hey I was wondering if there is any plan to add the visualizer to Streamlabs as a separate app? I use monitor cap for it on my second monitor. I am sure people would love to import their song info and everything using their current music app.

**Comment by danyals4241** [comment]
Agreed. They should make a browser source.

**Comment by marcopixel** [comment]
It's not possible with Rainmeter sadly, since it's not possible to export the skins as a "browser source" because they use a completly different way on how to render stuff and it would take years to rewrite Rainmeter to make it work. Also directly capturing does not work because of some weird rendering quirks on Rainmeter, but i'm not sure if that's fixable in the future though i'll recommend you asking in the official forums.

I'll close this as i'm sadly not able to help you on this.
