### ISSUE TITLE
VLC has audio; No album art or song info

### ISSUE THREAD

**Issue by DJ-TrainR3k** [MarcoPixel/Monstercat-Visualizer#26]
When I select VLC It visualizes the audio, but the album art and song info stay at "N/A". I am running the latest version of the skin and Rainmeter 4.0.0. According to the debug window in Rainmeter, it says "Chameleon: Could not get handle on C:\Users\[my_pc]\Documents\Rainmeter\Skins\Monstercat-Visualizer\0"

**Comment by MarcoPixel** [comment]
Thanks for your feedback!

I have to inform you that VLC 2.1 or higher is no longer supported with Rainmeter. There are some few workarounds in the official forums but for now i will remove support from the skin because it might be confusing.

Please check out the [forum post](https://forum.rainmeter.net/viewtopic.php?f=14&t=16981&start=10) regarding VLC player no longer working for more information.
