### ISSUE TITLE
Suggestion: Bigger Area For Mouse Detection to Fade Out?

### ISSUE THREAD

**Issue by Novas473** [marcopixel/Monstercat-Visualizer#276]
I hope I am not the only one wanting this feature...

I use two monitors when I am at home, and on my main monitor, I have whatever I am doing on it, being games, productivity, etc, but for my second monitor, I usually have my browser open, Discord, or Spotify open. What I like to do is place the visualizer on "Stay Topmost" (the album art and title are stayed topmost, as visualizer is just topmost, so then they aren't flickering between each other), and when my mouse hovers over any of them, they have the setting "Fadeout" on and transparency at 90%, along with click-through. However, when I hover my mouse over onto anything, I like how the visualizer has like, a big box for detecting the mouse, but I want the album art and title to do the same with the same range. They will, currently, only fade out if the mouse is right above them. Is there any way you can make it where you can set how large the area of effect can be?

https://i.gyazo.com/6e3d9434b8a85538d948b9b715343160.gif

**Comment by marcopixel** [comment]
Sadly this is out of scope for this skin, since it's really specific and doesn't save a practical use for the average user.

But you could add this feature yourself by adding a transparent shape above the media information and trigger the fade out with that. For that recommend you either go to the [Rainmeter forums](https://forum.rainmeter.net/) or the [unofficial discord](https://discord.com/invite/rainmeter) for additional help :)
