### ISSUE TITLE
Glitched Bars

### ISSUE THREAD

**Issue by Karannzz** [marcopixel/Monstercat-Visualizer#277]
### Description

Just installed this skin, and the bars for me are very glitched, i dont know what the problem is or the fix, however could I please get some assistance
![image](https://user-images.githubusercontent.com/20629325/73685050-51998400-46bd-11ea-8079-4ee423d4e268.png)
 

### Versions

[IMPORTANT: Please fill out the version numbers so we can properly look for your issue.]

[You can remove this section when posting an feature request]

* Rainmeter Version: Rainmeter 4.3.0.3298 (64-bit)
* OS Version: 
* Skin Version: 2.1.0
* Spotify Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#PluginsTab]

### Additional notes/images

[If you have any additional infos you can give us, please write them down]

**Comment by marcopixel** [comment]
This might be caused by some sort of faulty rendering either caused by your GPU or by Rainmeter. You can try to update Rainmeter, [disable hardware acceleration](https://docs.rainmeter.net/manual/user-interface/manage/#SettingsTab) and reinstall the skin completly.

I will close this issue for now, but if the issue still persists please comment down below!

**Comment by tooruu** [comment]
sussy baka 😌
