### ISSUE TITLE
Request: Support for more than one music player

### ISSUE THREAD

**Issue by Alquin12** [marcopixel/Monstercat-Visualizer#280]
Hello, I tend to use more than one music player, including Spotify, Web, Google Play Music Desktop Player and so it'll be awesome if there was the ability to select several music players to use with Monstercat Visualizer.

**Comment by marcopixel** [comment]
Sadly that's not possible with Rainmeter directly since specific plugins can only detect a single player and need to be restarted to fetch other data. You could technically manually add all the different measures to detect a specific player, but then you need to write a switching logic and it would also add additional strain on your PC which might cause performance issues.
