### ISSUE TITLE
Plexamp support

### ISSUE THREAD

**Issue by Azzhoe** [marcopixel/Monstercat-Visualizer#296]
Could you please make this work with Plexamp?

**Comment by marcopixel** [comment]
Sorry, but we can't add Plexamp because it's **not supported** by any of the currently used plugins ([NowPlaying](https://docs.rainmeter.net/manual/measures/nowplaying/), [WebNowPlaying](https://github.com/tjhrulz/WebNowPlaying)) and there is **no specific plugin made for it** yet.

If someone decided to make a plugin for Rainmeter, we can add it but for now it's not possible.
