### ISSUE TITLE
slow performance on Rainmeter 4.4 beta when running fullscreen video games

### ISSUE THREAD

**Issue by DIGIN4** [marcopixel/Monstercat-Visualizer#311]
### Description
The skin stops looking smooth if there's a game running when using Rainmeter v4.4 beta, works fine on v4.3 final

### Versions
* Rainmeter Version: 4.4 Beta Release
* OS Version: Windows 10 2004
* Skin Version: 2.1.0
* Spotify Version: Not installed

Tried modifying Smoothing level and Sound resolution, also disabling and enabling Hardware acceleration in Rainmeter but same issue still.

**Comment by marcopixel** [comment]
This might be because of insufficient hardware resources or having hardware acceleration enabled. 

Check if you have hardware acceleration enabled and if disabling/enabling it causes any differences. You can find the setting under **Manage -> Settings -> Use hardware acceleration (Requires restart)**.
