### ISSUE TITLE
Cant drag this skin

### ISSUE THREAD

**Issue by justclassy** [marcopixel/Monstercat-Visualizer#314]
So I got the visualizer to work and it moves when sound is playing. My problem is that I can't move it at all. When I try to make it draggable through rainmeter it has it locked so I can't change it. Any solutions?

**Comment by eileenthg** [comment]
Have you tried unchecking "Keep on screen" at Rainmeter manager for the visualizer?

**Comment by justclassy** [comment]
No but I’ll be sure to try that. If this changes anything I late found out that I can’t move any of my skins on Rainmeter. I tried deleting and reinstalling some skins but it didn’t change anything.

**Comment by justclassy** [comment]
So I tried your suggestion but it didn't seem to work at all. Here's what is looks like
![image](https://user-images.githubusercontent.com/69696596/90316725-fa306800-ded8-11ea-814a-b6c6e279cae5.png)

**Comment by eileenthg** [comment]
Why is "Draggable" off? That setting is supposed to be on if you want to drag the visualizer around.
ah i guess that's the problem. don't know how to fix that.

**Comment by hshams28** [comment]
Having the same issue here and have tried the above mentioned as well. Also to note: the "Draggable" option is also greyed out for me.

**Comment by sctanf** [comment]
Are other skins also not draggable? Try going to the Rainmeter manager and click on the settings tab at the top, there is an option that disables dragging. If it is on, that's probably why you can't drag anything, and you have to turn it off so the other draggable toggles will stop being grey.

**Comment by marcopixel** [comment]
This seems to be an issue with your local Rainmeter installation, check if you have the **latest version of Rainmeter installed** and check if the **[Rainmeter.ini](https://docs.rainmeter.net/manual/settings/#RainmeterIni) file has correct permissions** (needs to have write access).

Since it's about a month since the last reply, i'll assume this issue has been fixed. If not, please reply as a comment down below!
