### ISSUE TITLE
[Request] Thumbs-Up/Favorite Support?

### ISSUE THREAD

**Issue by livejamie** [marcopixel/Monstercat-Visualizer#321]
### Description

It would be nice to be able to heart/thumbs-up songs when hovering over the cover image to control media.

### Additional notes/images

YTMDesktop does this pretty well

![image](https://user-images.githubusercontent.com/49513/92983978-a5dac280-f45b-11ea-98c6-552d67f6ed59.png)

**Comment by marcopixel** [comment]
Technically it would be possible to add this feature to **WebNowPlaying** supported players, but since this feature doesn't work on local tracks & it's not supported on all players even with the plugin it will not be added.

If you want to add this functionally yourself, you can start here: https://docs.rainmeter.net/manual/getting-started/creating-skins/
