### ISSUE TITLE
[Question] Change what song information to display? (Instead of Artist use Album Artist, etc)

### ISSUE THREAD

**Issue by nicamoq** [marcopixel/Monstercat-Visualizer#322]
What config should I change to change what media info to change?

For example,
![image](https://user-images.githubusercontent.com/27849412/93431597-ee302f80-f8f6-11ea-954e-16113a9fa10e.png)

I want it to display the Album Artist, which is:

![image](https://user-images.githubusercontent.com/27849412/93431704-1881ed00-f8f7-11ea-8257-9ffe93159aa0.png)

**Comment by marcopixel** [comment]
Sadly both [NowPlaying](https://docs.rainmeter.net/manual/measures/nowplaying/) & [WebNowPlaying](https://github.com/tjhrulz/WebNowPlaying#measure-types) (the plugins used to fetch song infomartion) only support `Artist` as option. If you want, you could try and ask in the Rainmeter forums if they add it to Rainmeter. Sadly i cannot help you further with  so i will close this issue here.
