### ISSUE TITLE
WebNowPlaying integration from YTMDesktop causes Cover Art to blink on and off randomly.

### ISSUE THREAD

**Issue by remorsecodex** [marcopixel/Monstercat-Visualizer#325]
### Description

I just set up YTMDesktop integration via WebNowPlaying with RainMeter for my desktop where I use Monstercat Visualizer to show album art, spectrometer, and track info. It all works fine except that the cover art blinks (momentarily shows the default Monstercat cover art) at random intervals.

### Versions

* Rainmeter Version: 4.4.0.3404 beta
* OS Version: Windows 10 Enterprise N v 10.0.19041 x64
* Skin Version: 2.1.0
* Spotify Version: n/a

### Additional notes/images

The shortest time between blinks that I've timed is about 3s, and the longest is about 45s.

Play music in YTMDesktop with WebNowPlaying reporting to another app/integration that displays cover art.
Observe blinking at random.

Expected behavior
Cover art to show without blinking like this - steady, only changing when albums change while playing music.
 
Checked the rainmeter logs and found this:

ERRO (20:39:12.018) monstercat-visualizer\visualizer.ini - [MeasureWebParser]: (Fetch error) The operation timed out (ErrorCode=12002)
ERRO (20:39:34.921) : Unable to download album art to: C:\Users\Username\Documents\Rainmeter\Skins\monstercat-visualizer@Resources\images\coverWeb.png

The above (unable to download album art error) appears in the logs whenever the blinking occurs.

**Comment by tjhrulz** [comment]
First I have heard of this application, however looking over its source code this application seems to be emulating the extension and making a connection to WebNowPlaying's Rainmeter plugin. I will have to look into the exact reason it is causing this issue, if I had to guess from a quick glance they do not have how the extension communicates 100% right and are sending this data constantly and not just when a change has been detected.

However this issue is on there end not MVs, I will go on ahead and cross reference my findings on your issue on the ytmdesktop github.

**Comment by remorsecodex** [comment]
Thank you, I wasn't sure exactly where the fault lay. I did a post there first, but the error logs made me think it could have been a rainmeter/monstercat issue.
