### ISSUE TITLE
Any Way to Change the Color of Each Bar Individually

### ISSUE THREAD

**Issue by Xedict** [MarcoPixel/Monstercat-Visualizer#35]
I've looked through the .ini's and settings but I can't seem to find a way to do this. What I'm trying to do is to give the visualizer a gradient effect, where the color will slowly transition to another from left to right.

Am I just being blind or is there actually no way to do this right now?

Thanks in advance.

**Comment by MarcoPixel** [comment]
Thanks for your feedback!

There is currently no way to do this without breaking the generator code for the bars. So if you want to change the color of each bar manually you have to do it by removing the Factory code in visualizer.ini and set each color to the bars in @Resources\include\MeterBars.inc. 

For that, i would recommend checking out the Rainmeter documentation here:

https://docs.rainmeter.net/manual/getting-started/

I will close this issue because it will not be implemented because it would break one of the main features of this skin.
