### ISSUE TITLE
Spotify goes black and don't pull the cover and artist name

### ISSUE THREAD

**Issue by OrenML** [MarcoPixel/Monstercat-Visualizer#364]
I've done all the steps mentioned in: 
https://github.com/marcopixel/Monstercat-Visualizer/wiki/WebNowPlaying-Spotify
The Spotify worked and also the visualiser, sometimes it stops to pull the artist name and cover so I repeat the stages and sometimes reinstall Spotify and it worked.
This time it doesn't work, all I got is black screen Spotify, though if I press space it starts playing the last song but I can't navigate through the app and also it doesn't pull the name of the artist and cover.
How can I solve it?
i'm attaching screenshots:

![Screenshot 2021-07-14 18 43 36](https://user-images.githubusercontent.com/87436696/125651446-62995512-c031-45a6-a13e-f4743e6c1de5.png)
![Screenshot 2021-07-14 18 44 31](https://user-images.githubusercontent.com/87436696/125651511-ded9ab7b-e790-47ae-b579-8cc3421336e6.png)
![Screenshot 2021-07-14 18 45 32](https://user-images.githubusercontent.com/87436696/125652062-4c74096b-41ab-4c2d-8e00-c749e72b96b9.png)

Rainmeter 4.4.0.3408 beta (64-bit)
Windows 10 Home 2009 64-bit (build 19042) - English (1033)
Skin Version: Version=2.1.0
Spotify Version: 1.1.63.568

**Comment by NoahJMC** [comment]
The same exact thing just happened to me. I've reinstalled several times and followed every step perfectly, it was working fine before, but all of a sudden its doing this. I hope this gets solved soon.

**Comment by icantpronouncethis** [comment]
Same here. It actually happened after a recent update from Spotify. Hope this info kinda helps.

**Comment by astronaut954** [comment]
Same here, reinstalled Spotify, followed all instructions, and all I get it's a black screen.
Also, it will show an error in Powershell saying: Cannot find symbol for Custom app React symbols

**Comment by vanduong0504** [comment]
Not only me.

**Comment by marcopixel** [comment]
This is an issue caused by **Spotify** having an update and breaking [spicetify-cli](https://github.com/khanhas/spicetify-cli) (the tool used for adding the webnowplaying functionality). 

There is a [workaround ](https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-877558177) though by downgrading the version of Spotify to fix the issue temporarily, everyone else has to wait for @khanhas to publish a new version to fix the issue. You can read more about this problem here: https://github.com/khanhas/spicetify-cli/issues/845
