### ISSUE TITLE
Web Audio Player & Hide on missing audio input

### ISSUE THREAD

**Issue by DeusProx** [MarcoPixel/Monstercat-Visualizer#37]
Hello! I just found out about rainmeter and your awesome visualizer but I mostly listen to music online (youtube, soundcloud, spotify, amazon music) and so i can't hide it automatically. It would be cool if you could add a feature which doesn't visualize if there is no music. If that's not possible due to limitations it would be cool if it doesn't visualize if there is no open browser

**Comment by MarcoPixel** [comment]
Thanks for your feedback!

I am sorry to inform you that i will not implement your feature because of the work implementing this feature and also maintaining it when there will be changes in the future.

You can try to create this feature yourself as Rainmeter is really easy to get started with the help of the [Rainmeter documentation](https://docs.rainmeter.net/) and the official [Rainmeter forums](https://forum.rainmeter.net/).
