### ISSUE TITLE
A way to reduce latency on high-end PCs ?

### ISSUE THREAD

**Issue by cab13140** [MarcoPixel/Monstercat-Visualizer#46]
Hey bud !
Awesome skin, just thank you !

Can the plugin you're using for FTT (not an expert in that 😢 ) be edited to get quicker response times ? I usually get around half a second; Changing the FTT option doesn't seems to change anything, neither do the options in the config ini.

Thanks a lot, again ! Of course I won't be mad if this is impossible. The skin is complete enough for now 😄

**Comment by MarcoPixel** [comment]
You can also try reducing the Smoithing value and if you open the variables.ini (under Documents/Rainmeter/Skins/Monstercat-Visualizer/@Resources) you can also adjust the FFTAttack and FFTDelay values.

But please remember that even on the lowest settings there will be delay because of how this plugin works.

Am 05.05.2017 16:49 schrieb cab13140 <notifications@github.com>:

Hey bud !
Awesome skin, just thank you !

Can the plugin you're using for FTT (not an expert in that 😢 ) be edited to get quicker response times ? I usually get around half a second; Changing the FTT option doesn't seems to change anything, neither do the options in the config ini.

Thanks a lot, again ! Of course I won't be mad if this is impossible. The skin is complete enough for now 😄

**Comment by cab13140** [comment]
Okay. Adjusting the Attack value is just enough to get a quarter of second less latency. Thanks, closing the issue.
