### ISSUE TITLE
Moving genres and matching colors from MesureStyling.inc to variables.ini

### ISSUE THREAD

**Issue by cab13140** [MarcoPixel/Monstercat-Visualizer#59]
_[You may add Feature Request tag]_
It could be great if the genres and matching colors could be moved from [_MesureStyling.inc_](https://github.com/MarcoPixel/Monstercat-Visualizer/blob/master/%40Resources/include/MeasureStyling.inc#L61) to _variables.ini_
This would add more customization without needing deep code search and critical files editing.

Also, with that edit made, it could be a great way for the **Open Variables** option in context menu to comeback alongside the visual settings

**Comment by tjhrulz** [comment]
If you are using a version with the new color system I wrote it should be using variables now instead of the old style stuff. The setting of new colors for the variables and pushing it to the coloor change group is just handled in that include file. However I do agree it may be useful to explain how to use them in the about section or something.

**Comment by tjhrulz** [comment]
Also you may want to see https://github.com/MarcoPixel/Monstercat-Visualizer/issues/43

**Comment by tjhrulz** [comment]
Given that the request for the variables had been added and the other away exists I'm gonna close this.

**Comment by cab13140** [comment]
Thanks for consideration.
