### ISSUE TITLE
Add Support for Tidal!

### ISSUE THREAD

**Issue by GRiZzLY1510** [MarcoPixel/Monstercat-Visualizer#68]
Hey There!
Not sure if it's possible but I would love if you could Tidal Support for the Player!

**Comment by tjhrulz** [comment]
Doing a real quick once over it looks like they have both a desktop and a web app. I will have to look more in depth when I am in front of my computer but likely the desktop app either will be very limited or will not work. However I will likely be able to support the web app with WebNowPlaying.

**Comment by tjhrulz** [comment]
Does not look like it would be possible to add support for the desktop app. It does seem plausible that I could add support for the web app but since I need a premium account to get it working I will wait till I after I go on my vacation that way I have the time to get it done right. ETA first week of august.

I am gonna go on ahead and leave this issue open until I can finish working on it then.

**Comment by tjhrulz** [comment]
Back from vacation, I'll be looking at support tonight.

**Comment by tjhrulz** [comment]
Finished adding support via WebNowPlaying. It will be supported with the next release of the monstercat visualizer. 
https://github.com/tjhrulz/WebNowPlaying-ChromeExtension/commit/c7403b8ffd3e99c31118e2bfb77c50c7faf878f9
