### ISSUE TITLE
Issue with memory leaking

### ISSUE THREAD

**Issue by lyn3x5** [MarcoPixel/Monstercat-Visualizer#69]
After leaving my PC on for quite some time I loaded the Google Play Music Player and started playing music with the visualizer active. I noticed that it was very sluggish to react to the music which prompted me to open my Task Manager, and I noticed it was using almost 4gb of memory (which explained the sluggishness). After unloading everything related to the music, I notice that the Monstercat Visualizer was the cause of the issue. POssible the GPMP plugin.

**Comment by MarcoPixel** [comment]
Could you please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/) and post it in here.

Also please write down your OS version, Rainmeter version, GPMDP plugin version and skin version.

**Comment by lyn3x5** [comment]
Windows 10
RM Version 4.0.0 r2746
1.3.1
Skin version 1.7.1
http://grabilla.com/07713-61c48e34-dd7a-48fe-8420-c8393deb3f4e.html

I did update to the 1.4 version for the plugin, I will monitor from here.

I also noticed, that if you have to many audio devices, the list in the native settings for the visualizer it will not show all audio devices through the change audio device setting. Though default was a sufficient workaround it would be good to expand this. Possibly just a simple dropdown menu?

http://grabilla.com/07713-d0a9d9fe-bbb6-4fdc-a3af-dc57d70ccf80.html

Also sorry, I do this for a living.

**Comment by lyn3x5** [comment]
As an update,

Took Rainmeter to the latest update (r2824), and with the plugin updated as well the memory continues to climb, currently at 320mb in about 15 minutes after updating the RM version.

**Comment by MarcoPixel** [comment]
Thanks for the fast response!

From the logs and all the other stuff it seems to be fine, even with the error from MiniWeather (cause stuck WebParser might lead to an RAM leak).

@tjhrulz might know what the issue is as he is the creator of the plugin, maybe he knows a way to show the debug logs or something.

**Comment by tjhrulz** [comment]
I'm out sailing at the moment so I'll check when I get home and we can go through some debugging steps. I would say maybe something with Rainmeter bone some of the memory management with c# plugins but you are not using the beta branch and I have seen no memory leaks with my plugin since the first one.

What is your connection state when it happens? Also if you disconnect/connect does it have away.

**Comment by tjhrulz** [comment]
Okay back home now, looking into everything on my end I am not seeing any memory leak over here running the exact same version of everything you had before and the 1.4 version of my plugin for about the past 3 days. 
It may be something else is the cause, what all skins do you have loaded? Since you seem to have QA experience maybe try cloning the Rainmeter source, building a copy, and run some memory profiling to see what skin/plugin has all that memory allocated to it.

**Comment by tjhrulz** [comment]
Any updates on this? I still have been unable to replicate this on my end.

**Comment by tjhrulz** [comment]
Closing issue due to no response and lack of info about memory leak. My tests show if he had one it is an old version or not caused by gpmdp.
