### ISSUE TITLE
Visualizer seems to fill the pagefile when also running ASIO4ALL on FL Studio.

### ISSUE THREAD

**Issue by Noiztox** [MarcoPixel/Monstercat-Visualizer#80]
I have been wondering for weeks what keeps crashing my FL Studio and my computer in the process, and I think I have pinpointed the source to Monstercat Visualizer, as the commit charge stops rising when I unload the visualizer.ini in Rainmeter and keeps rising again when I load it back. Might of course also be Asio's or FL's fault or who knows what.

Visualizer 1.7.1
Rainmeter 4.0
OS: Windows 10 64-bit

**Comment by tjhrulz** [comment]
Wait are you saying that it is filling up your pagefile and skipping RAM? That would be an odd memory leak. Likely caused by the audio level plugin. 

It may be FL Studio tries to pull the audio sources and gets in a fighting match with the audio level plugin.

Given we do not manage that plugin or FL studio there is little we can do. Likely though I would blame FL studio.

**Comment by Noiztox** [comment]
Yep, physical RAM stays untouched. 

ASIO4ALL has been known for having some issues, so I wouldn't wonder if it has something to do with it. Wanted to bring this issue to your attention anyway.

I'll just have to turn off the visualizer when I start FL. Thanks anyway!

**Comment by tjhrulz** [comment]
Alright well if you want to try to report it to others who may know of a fix you could post about it in the Troubleshooting guide for it in the forums: https://forum.rainmeter.net/viewtopic.php?t=23348 or in the plugins board https://forum.rainmeter.net/viewforum.php?f=18

You also I guess could try the IRC and see what they say.
