### ISSUE TITLE
Song information and bars not hiding with WebNowPlaying plugin on Chrome

### ISSUE THREAD

**Issue by raitono** [MarcoPixel/Monstercat-Visualizer#89]
I am using this with Pandora and the elements don't hide when the music is paused or when Chrome is closed. They disappear if I change to another player, but come back when I change back to WebNowPlaying. The Chrome setting to "Continue running background apps when Google Chrome is closed" is disabled.

**Comment by tjhrulz** [comment]
Oh shoot I did not think about that. Monstercat visualizer checks to see if the play state is stopped and not if the player is open for that feature. WebNowPlaying caches info on the Rainmeter side and deletes it once the tab is closed. However if you close your last tab it still keeps that info and since WebNowPlaying does not really have a stopped state on most sites it will never be stopped. I am not sure why I coded WebNowPlaying that way and will change it in the next release.

In the meantime though you can change this by changing MV to check the player status instead of state. To do this navigate to %UserProfile%\Documents\Rainmeter\Skins\Monstercat-Visualizer\@Resources\include and open MeasureWeb.inc. Towards the bottom of that file should be a section that looks like
```
[MeasureAutoHideWebNowPlaying]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=State
IfBelowValue=1
IfBelowAction=[!HideFade][!HideFade "#ROOTCONFIG#\Song Information"]
IfEqualValue=1
IfEqualAction=[!ShowFade][!ShowFade "#ROOTCONFIG#\Song Information"]
IfAboveValue=1
IfAboveAction=[!ShowFade][!ShowFade "#ROOTCONFIG#\Song Information"]
Disabled=#DisableAutoHide#
UpdateDivider=100
```
Change `PlayerType=State` to `PlayerType=Status`
